### PR TITLE
Fix Smooth Scroll Issue #6

### PR DESCRIPTION
**Pull request by Tuhin114**

### CODE REVIEW

**Comment by krishnagitcontri** [comment]
@Tuhin114 Why your PR not Merged?

**Comment by Tuhin114** [comment]
> @Tuhin114 Why your PR not Merged?

**Comment by Tuhin114** [comment]
I don't know.....I think they are not active yet

**Comment by TeeWrath** [comment]
@Tuhin114 Thanks for contribution

**Pull request merged**
